### ISSUE TITLE
An optional field is required when submitting form

### ISSUE THREAD

**Issue by OmarDahmen** [bluelibs/bluelibs#135]
**Describe the bug**
An optional field is required when submitting form

**To Reproduce**
* Collection file :
```
field({
      id: "archivingReason",
      type: field.types.ENUM,
      enumValues: ["CANCELED", "REFUSED", "LOST"], // REFUSED / REJECTED
      isRequired: false,
    }),
```
* Generated Input service file : `microservices/api/src/bundles/AppBundle/services/inputs/ClientRequestInsert.input.base.ts`
```
@Is(a.string().oneOf(Object.values(ClientRequestArchivingReason)).required())
  archivingReason?: ClientRequestArchivingReason;
```

**Expected behavior**
* Generated Input service file : `
```
@Is(a.string().oneOf(Object.values(ClientRequestArchivingReason)))
  archivingReason?: ClientRequestArchivingReason;
```

**LOG**
```
{
    "message": "archivingReason is a required field",
    "locations": [
        {
            "line": 2,
            "column": 3
        }
    ],
    "path": [
        "ClientRequestsInsertOne"
    ],
    "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
            "value": {
                "activity": "PLUMBING",
                "isArchived": false,
                "status": "CLIENT_REQUEST",
                "agencyId": null,
                "clientRequest": "ddddddddddd",
                "emergencyLevel": "IN_THE_NEXT_FEW_DAYS",
                "heaterMaintenanceContractId": null,
                "requestTypeId": "61a6380f455e75b95d0be96f",
                "source": "WEBSITE",
                "subjectId": "61a637e7455e75b95d0be96e"
            },
            "path": "archivingReason",
            "type": "required",
            "errors": [
                "archivingReason is a required field"
            ],
            "params": {
                "path": "archivingReason"
            },
            "inner": [],
            "name": "ValidationError",
            "message": "archivingReason is a required field",
            "stacktrace": [
                "ValidationError: archivingReason is a required field",
                "    at createError (/home/omar/dev/belett-2/microservices/api/node_modules/yup/lib/util/createValidation.js:54:21)",
                "    at /home/omar/dev/belett-2/microservices/api/node_modules/yup/lib/util/createValidation.js:72:107",
                "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
            ]
        }
    }
}
```

**Desktop :**
 - OS: [Ubuntu 20.04.3 LTS]

**Additional context**
I'm using "@bluelibs/x": "1.6.4"

**Comment by theodorDiaconu** [comment]
Released @bluelibs/x@1.6.6
