### ISSUE TITLE
Blueprint - Self referencing models

### ISSUE THREAD

**Issue by qfl1ck32** [bluelibs/bluelibs#200]
When trying to create a model that is referencing itself, e.g.:

```
const Person = sharedModel({
  fields: [
     field.string("name"),

    field.object("dad", {
        model: () => Person,

       isRequired: false, // okay, bad joke
   })
  ]
})
```

the blueprint will fail:

```
Error copying template over:  {
  filePath: 'src/bundles/UIAppBundle/pages/NoteModelsManagement/config/NoteModels.i18n.json'
} RangeError: Maximum call stack size exceeded
    at @bluelibs/x/src/studio/models/Field.ts:267:43
    at Array.forEach (<anonymous>)
    at Field.getSelfAndAllNestedFields (@bluelibs/x/src/studio/models/Field.ts:267:35)
```

**Comment by Fen747** [comment]
Hey [qfl1ck32](https://github.com/qfl1ck32) !
You can't have a model referencing itself, as it would lead to infinite recursivity when dealing with object models generation.
What you could do however, is to have an optional `relation` from a "Person" collection to itself.
And if that `Person` model is shared between several collections, you can simply replace it with a relation to `Persons`.

**Comment by qfl1ck32** [comment]
@Fen747 Hello! My real use case is a bit different:

```
export const Field = sharedModel({
  id: "Field",

  fields: [
    field.string("id"),

    field.string("name"),

    field.boolean("isArray"),

    field.enum("type", {
      enumValues: ["BOOLEAN", "ENUM", "NUMBER", "STRING", "OBJECT"],
    }),

    field.object("model", {
       model: () => Field,

       isRequired: false,
   }),
```

I want to let a user create a Field which might be of type `OBJECT`, and, therefore, he would need to input the model (which is a Field) for it. I guess it should be possible to do such a thing, with a few adjustments to BluePrint :)

**Comment by Fen747** [comment]
`he would need to input the model (which is a Field) for it`
I guess you mean an array of Field ? (as there might be several fields in an object) ? 😄 

Why do you need it to be a shared model ? Can't it be a collection with inversed relations to it ?

You could have :
```typescript
export const Forms = collection({
  id: "Forms",
  fields: [
    field.string("name", {
      isRequired: true,
    }),
  ],
  relations: [
    relation({
      id: "fields",
      to: "Fields",
      isMany: true,
      representedBy: "name",
    }),
  ],
});

export const Fields = collection({
  id: "Fields",
  fields: [
    field.string("id"),
    field.string("name"),
    field.boolean("isArray"),
    field.enum("type", {
      enumValues: ["BOOLEAN", "ENUM", "NUMBER", "STRING", "OBJECT"],
    }),
    field.object("model", {
       model: () => Field,
       isRequired: false,
   })
  ],
  relations: [
    relation({
      id: "subfields",
      to: "Fields",
      isMany: true,
      representedBy: "name",
      isRequired: false // we want it optional as this relation will be set only when field.type === "object"
    }),
  ],
});
```

**Comment by qfl1ck32** [comment]
Yep, an array of fields, my bad.

Also, yes, that would solve the problem. Truth is, initially, I thought having a simple model would be enough, so I didn't opt for a collection. Probably, this is the better idea, now. Thank you!

Though, would there maybe still be cases where you'd want a self-referencing model?

**Comment by theodorDiaconu** [comment]
I think this could be solved through an API like field.object("dad", { model: 'self' });

**Comment by Fen747** [comment]
Well, the benefit from having self-referencing models would the same as having relations on nested-fields : it would allow to reduce the number of ping-pong between the server and the database, as in [qfl1ck32](https://github.com/qfl1ck32), I don't se how (Hyper)Nova could avoid querying the same collection multiple times

**Comment by qfl1ck32** [comment]
This is exactly what I was trying, to reduce the number of back-n-forths between the api & the database. Having everything stored in just one field, in a document, would've allowed for querying only that field. With self-referencing *relations*, there are calls to retrieve each field, if I am not mistaken :)

**Comment by theodorDiaconu** [comment]
The solution for self referencing is like this:
```
createFields() { return [] }

const Tree = collection({
   fields: [
      ...createFields(),
      field({ id: "children", isArray: true, subfields: createFields() }); 
   ],
});
```
